version: '3'
services:
  wordpress:
    image: wordpress
    container_name: wp_server209
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wp_database209
      - WORDPRESS_DB_USER=wp_user209
      - WORDPRESS_DB_PASSWORD=alumno209
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    container_name: servidor_mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=alumno209
      - MARIADB_DATABASE=wp_database209
      - MARIADB_USER=wp_user209
      - MARIADB_PASSWORD=alumno209
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    restart: always

volumes:
  mariadb_data:
  wordpress_data:
